apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/kloe-b/p4-order-microservice/p4-order-microserivce:latest
          ports:
            - containerPort: 8080  
          env:
            - name: SECRET_KEY
              value: "your_secret_key"
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              value: "redis-service.default.svc"
            - name: REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: regcred
            
